### ISSUE TITLE
Missing TTS Voice

### ISSUE THREAD

**Issue by mati3230** [Cognigy/CognigyUnity3DClient#2]
SpeechLib TTS is created but no voice output appears. I saved the clip in the audio source and watched the amplitude (see attachment). Here no amplitude appears. 

![generatedaudioclipexample](https://user-images.githubusercontent.com/20703285/29878298-74f8c662-8da2-11e7-82dc-6d2af08dd7a4.jpg)

**Comment by j-sommer** [comment]
Hi Marcel,

the problem is that you can't display the amplitude of the at runtime generated audio clip in play mode. If you want to check the amplitude you can save the received audio clip as a .wav-file and then check the amplitude in the editor mode. To save the audio clip you can use: https://gist.github.com/darktable/2317063

![tts_sound_inspector](https://user-images.githubusercontent.com/22472416/29942947-e1ea538a-8e97-11e7-864f-24fa1a9831de.PNG)

Best Regards,
Jan

**Comment by mati3230** [comment]
Hey Jan,

I cloned the repo again and tried the plugin and it works without any error
:). TTS and STT are working, but I had to turn on Windows Speech
Recognition on Windows 10. Therefore, Now I can communicate with cognigy ai
server and I think the plugin is very cool - very good work :).

Best Regards,

Marcel

2017-08-31 22:03 GMT+02:00 Jan Sommer <notifications@github.com>:
